### ISSUE TITLE
Support for IEEE and ACM Digital Library

### ISSUE THREAD

**Issue by theisjendal** [flcong/get-article-file-name#1]
It is a very nice pluging but support for these two sites would be very nice as they are quite big :-)

Best regards
Theis

**Comment by flcong** [comment]
No problem. Since I am not in this area, could you list the URLs of any papers on these two websites (e.g. any paper you are searching now) so I can take a look?

**Comment by theisjendal** [comment]
Sorry for the late reply but the following could be examples: 

- https://dl.acm.org/doi/abs/10.1145/3292500.3330989?casa_token=Y5MnRf_ejP8AAAAA:Xk6_iijuOrZb0xHRiu2masSw9xr3V1x2parpKmb5YzOG56EJyMOM2OeDPFyQ51frkCvxBSPL7UQgm68
- https://ieeexplore.ieee.org/abstract/document/8938875?casa_token=0lVRZ2krRBcAAAAA:5VWkweGl1ZzstkfjdMek7ux24xnL86hqVzzeowlZbavK5UN1NokeNMmqORRo59dFra7j8fwgFGo

**Comment by flcong** [comment]
Thank you. Features added in v2.0.9. Pending review. Should be automatically updated soon.
